[package]
name = "basic-add-wasm"
version = "0.1.0"
authors = ["Parity Technologies <admin@parity.io>"]

[dependencies]
basic-add = { path = ".." }
polkadot-parachain = { path = "../../../parachain", default-features = false }
wee_alloc = { version = "0.4.1" }
pwasm-libc = { version = "0.2" }
tiny-keccak = "1.4"

[profile.release]
panic = "abort"
lto = true

[lib]
crate-type = ["cdylib"]
